export const filterPresets: Record<string, any> = {
  DAILY_RENT: {
    city: "Город",
    district: "Район",
    min_price: "Цена",
    max_price: "Цена",
    start_date: "Дата",
    end_date: "Дата",
    can_be_delivered: "Доставка",
  },
  RENT_AUTO: {
    without_deposit: "Депозит",
    transmission_type: "Тип трансмиссии",
    city: "Город",
    fuel_type: "Тип топлива",
    car_body_type: "Тип кузова",
    car_category: "Класс авто",
    min_year: "Год",
    max_year: "Год",
    min_price_per_day: "Цена",
    max_price_per_day: "Цена",
  },
  AUTO_SERVICES: {
    city: "Город",
    district: "Район",
    min_price: "Цена",
    max_price: "Цена",
  },
  BUY_AUTO: {
    city: "Город",
    min_price: "Цена",
    max_price: "Цена",
  },
  DRIVER_JOBS: {
    city: "Город",
    district: "Район",
    min_price: "Зарплата",
    max_price: "Зарплата",
    can_be_delivered: "Авто предоставляется",
  },
};
