export const cars = [
  {
    common: {
      id: "list_1",
      photos: ["/car.png"],
      title: "Аренда Li L7 2024",
      description: "",
      ads: true,
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
  },
  {
    common: {
      id: "list_12",
      photos: ["/car.png"],
      title: "Аренда Li L7 2024",
      description: "",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
  },
  {
    common: {
      id: "list_123",
      photos: ["/car.png"],
      title: "Аренда Li L7 2024",
      description: "",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
  },
  {
    common: {
      id: "list_1234",
      photos: ["/car.png"],
      title: "Аренда Li L7 2024",
      description: "",
      ads: true,
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
  },
  {
    common: {
      id: "list_12345",
      photos: ["/car.png"],
      title: "Аренда Li L7 2024",
      description: "",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
  },
  {
    common: {
      id: "list_123456",
      photos: ["/car.png"],
      title: "Аренда Li L7 2024",
      description: "",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
  },
  {
    common: {
      id: "list_1234567",
      photos: ["/car.png"],
      title: "Аренда Li L7 2024",
      description: "",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
  },
  {
    common: {
      id: "list_12345678",
      photos: ["/car.png"],
      title: "Аренда Li L7 2024",
      description: "",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
  },
  {
    common: {
      id: "list_123456789",
      photos: ["/car.png"],
      title: "Аренда Li L7 2024",
      description: "",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
  },
  {
    common: {
      id: "list_1234567890",
      photos: ["/car.png"],
      title: "Аренда Li L7 2024",
      description: "",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
  },
  {
    common: {
      id: "list_12345678901",
      photos: ["/car.png"],
      title: "Аренда Li L7 2024",
      description: "",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
  },
  {
    common: {
      id: "list_123456789012",
      photos: ["/car.png"],
      title: "Аренда Li L7 2024",
      description: "",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
  },
  {
    common: {
      id: "list_1234567890123",
      photos: ["/car.png"],
      title: "Аренда Li L7 2024",
      description: "",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
  },
  {
    common: {
      id: "list_12345678901234",
      photos: ["/car.png"],
      title: "Аренда Li L7 2024",
      description: "",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
  },
  {
    common: {
      id: "list_123456789012345",
      photos: ["/car.png"],
      title: "Аренда Li L7 2024",
      description: "",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
  },
  {
    common: {
      id: "list_1234567890123456",
      photos: ["/car.png"],
      title: "Аренда Li L7 2024",
      description: "",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
  },
  {
    common: {
      id: "list_12345678901234567",
      photos: ["/car.png"],
      title: "Аренда Li L7 2024",
      description: "",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
  },
  {
    common: {
      id: "list_123456789012345678",
      photos: ["/car.png"],
      title: "Аренда Li L7 2024",
      description: "",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
  },
  {
    common: {
      id: "list_1234567890123456789",
      photos: ["/car.png"],
      title: "Аренда Li L7 2024",
      description: "",
      ads: true,
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
  },
  {
    common: {
      id: "list_12345678901234567890",
      photos: ["/public/car.png"],
      title: "Аренда Li L7 2024",
      description: "",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
  },
];
