export const cars = [
  {
    listing: {
      id: "d18ec707-8f7c-4e9e-a4c4-bf6d2429f896",
      size: "large",
      carRentListing: {
        id: "4a1e9c2c-1e68-4e0c-90e4-4e210cf603ab",
        carContent: {
          id: "aea9cbbe-93b7-4e88-906d-85cd38209c41",
          userId: "deadbeef-dead-beef-dead-beefdeadbeef",
          brandId: "Li",
          modelId: "L7",
          yearOfCarProduction: 2024,
          fuelType: "FUEL_TYPE_DIESEL",
          transmission: "TRANSMISSION_TYPE_MANUAL",
          carBodyType: "CAR_BODY_TYPE_WAGON",
          vehicleSegment: "VEHICLE_SEGMENT_D",
          carOptions: {
            hasAirConditioning: false,
            hasChildSeat: true,
          },
          carCategory: "CAR_CATEGORY_ECONOMY",
          color: "Белый",
          photosUrl: ["car.svg", "car.svg", "car.svg"],
          createdAt: "2025-05-24T14:57:15.542674Z",
          updatedAt: "2025-05-24T14:57:15.542674Z",
        },
        userId: "deadbeef-dead-beef-dead-beefdeadbeef",
        listingOptions: {
          allowedForTaxi: false,
          allowedOnlyForPersonalUse: false,
          requireRussianCitizenship: false,
          buyoutPossible: true,
        },
        depositRequired: false,
        paymentPeriod: ["PAYMENT_PERIOD_DAILY"],
        pricePerDay: 2500,
        minimumRentalPeriod: 2,
        additionalInfo:
          "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д",
        createdAt: "2025-05-24T14:57:15.546472Z",
        updatedAt: "2025-05-24T14:57:15.546472Z",
        city: "Сочи",
        rentDuration: ["RENT_DURATION_FROM_DAY"],
      },
    },
  },
  {
    listing: {
      id: "d18ec707-8f7c-4e9e-a4c4-bf6d2429f899",
      size: "large",
      ads: true,
      carRentListing: {
        id: "4a1e9c2c-1e68-4e0c-90e4-4e210cf03ab",
        carContent: {
          id: "aea9cbbe-93b7-4e88-906d-85cd38209c41",
          userId: "deadbeef-dead-beef-dead-beefdeadbeef",
          brandId: "Li",
          modelId: "L7",
          yearOfCarProduction: 2024,
          fuelType: "FUEL_TYPE_DIESEL",
          transmission: "TRANSMISSION_TYPE_MANUAL",
          carBodyType: "CAR_BODY_TYPE_WAGON",
          vehicleSegment: "VEHICLE_SEGMENT_D",
          carOptions: {
            hasAirConditioning: false,
            hasChildSeat: true,
          },
          carCategory: "CAR_CATEGORY_ECONOMY",
          color: "Белый",
          photosUrl: ["car.svg", "car.svg", "car.svg"],
          createdAt: "2025-05-24T14:57:15.542674Z",
          updatedAt: "2025-05-24T14:57:15.542674Z",
        },
        userId: "deadbeef-dead-beef-dead-beefdeadbeef",
        listingOptions: {
          allowedForTaxi: false,
          allowedOnlyForPersonalUse: false,
          requireRussianCitizenship: false,
          buyoutPossible: true,
        },
        depositRequired: false,
        paymentPeriod: ["PAYMENT_PERIOD_DAILY"],
        pricePerDay: 2500,
        minimumRentalPeriod: 2,
        additionalInfo:
          "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д",
        createdAt: "2025-05-24T14:57:15.546472Z",
        updatedAt: "2025-05-24T14:57:15.546472Z",
        city: "Сочи",
        rentDuration: ["RENT_DURATION_FROM_WEEK"],
      },
    },
  },
  {
    listing: {
      id: "d18ec797-8f7c-4e9e-a4c4-bf6d2429f896",
      carRentListing: {
        id: "4a1e9c2c-1e68-4e0c-90e4-4e210cf603ac",
        carContent: {
          id: "aea9cbbe-93b7-4e88-906d-85cd38209c41",
          userId: "deadbeef-dead-beef-dead-beefdeadbeef",
          brandId: "Li",
          modelId: "L7",
          yearOfCarProduction: 2024,
          fuelType: "FUEL_TYPE_DIESEL",
          transmission: "TRANSMISSION_TYPE_MANUAL",
          carBodyType: "CAR_BODY_TYPE_WAGON",
          vehicleSegment: "VEHICLE_SEGMENT_D",
          carOptions: {
            hasAirConditioning: false,
            hasChildSeat: true,
          },
          carCategory: "CAR_CATEGORY_COMFORT_PLUS",
          color: "Белый",
          photosUrl: ["car.svg", "car.svg", "car.svg"],
          createdAt: "2025-05-24T14:57:15.542674Z",
          updatedAt: "2025-05-24T14:57:15.542674Z",
        },
        userId: "deadbeef-dead-beef-dead-beefdeadbeef",
        listingOptions: {
          allowedForTaxi: false,
          allowedOnlyForPersonalUse: false,
          requireRussianCitizenship: false,
          buyoutPossible: true,
        },
        depositRequired: false,
        paymentPeriod: ["PAYMENT_PERIOD_DAILY"],
        pricePerDay: 2500,
        minimumRentalPeriod: 2,
        additionalInfo:
          "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. дь",
        createdAt: "2025-05-24T14:57:15.546472Z",
        updatedAt: "2025-05-24T14:57:15.546472Z",
        city: "Сочи",
        rentDuration: ["RENT_DURATION_FROM_WEEK"],
      },
    },
  },
  {
    listing: {
      id: "d18ec707-8f7c-4e6e-a4c4-bf6d2429f896",
      ads: true,
      carRentListing: {
        id: "4a1e9c2c-1e68-4e0c-90e4-4e210cf503ab",
        carContent: {
          id: "aea9cbbe-93b7-4e88-906d-85cd38209c41",
          userId: "deadbeef-dead-beef-dead-beefdeadbeef",
          brandId: "Li",
          modelId: "L7",
          yearOfCarProduction: 2024,
          fuelType: "FUEL_TYPE_DIESEL",
          transmission: "TRANSMISSION_TYPE_MANUAL",
          carBodyType: "CAR_BODY_TYPE_WAGON",
          vehicleSegment: "VEHICLE_SEGMENT_D",
          carOptions: {
            hasAirConditioning: false,
            hasChildSeat: true,
          },
          carCategory: "CAR_CATEGORY_ECONOMY",
          color: "Белый",
          photosUrl: ["car.svg", "car.svg", "car.svg"],
          createdAt: "2025-05-24T14:57:15.542674Z",
          updatedAt: "2025-05-24T14:57:15.542674Z",
        },
        userId: "deadbeef-dead-beef-dead-beefdeadbeef",
        listingOptions: {
          allowedForTaxi: false,
          allowedOnlyForPersonalUse: false,
          requireRussianCitizenship: false,
          buyoutPossible: true,
        },
        depositRequired: false,
        paymentPeriod: ["PAYMENT_PERIOD_DAILY"],
        pricePerDay: 2500,
        minimumRentalPeriod: 2,
        additionalInfo:
          "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д",
        createdAt: "2025-05-24T14:57:15.546472Z",
        updatedAt: "2025-05-24T14:57:15.546472Z",
        city: "Сочи",
        rentDuration: ["RENT_DURATION_FROM_WEEK"],
      },
    },
  },
  {
    listing: {
      id: "e29fc818-9f8d-5f0f-b5d5-cg7e3530g9097",
      carRentListing: {
        id: "5b2f0d3d-2f79-5f1d-a1f5-5f321dg714bc",
        carContent: {
          id: "bfb0dcce-a4c8-5f99-a17e-96de4931a052",
          userId: "deadbeef-dead-beef-dead-beefdeadbeef",
          brandId: "AUDI",
          modelId: "AUDI_A6",
          yearOfCarProduction: 2022,
          fuelType: "FUEL_TYPE_PETROL",
          transmission: "TRANSMISSION_TYPE_AUTOMATIC",
          carBodyType: "CAR_BODY_TYPE_SEDAN",
          vehicleSegment: "VEHICLE_SEGMENT_E",
          carOptions: {
            hasAirConditioning: true,
            hasChildSeat: false,
          },
          carCategory: "CAR_CATEGORY_BUSINESS",
          color: "Черный",
          photosUrl: ["car-large.svg", "car-large.svg", "car-large.svg"],
          createdAt: "2025-05-25T10:30:00.000000Z",
          updatedAt: "2025-05-25T10:30:00.000000Z",
        },
        userId: "deadbeef-dead-beef-dead-beefdeadbeef",
        listingOptions: {
          allowedForTaxi: true,
          allowedOnlyForPersonalUse: true,
          requireRussianCitizenship: true,
          buyoutPossible: true,
        },
        depositRequired: true,
        paymentPeriod: ["PAYMENT_PERIOD_DAILY", "PAYMENT_PERIOD_WEEKLY"],
        pricePerDay: 3500,
        minimumRentalPeriod: 1,
        additionalInfo:
          "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д",
        createdAt: "2025-05-25T10:30:00.000000Z",
        updatedAt: "2025-05-25T10:30:00.000000Z",
        city: "Москва",
        rentDuration: ["RENT_DURATION_FROM_DAY", "RENT_DURATION_FROM_WEEK"],
      },
    },
  },
  {
    listing: {
      id: "d18ec707-8f7c-1e9e-a4c4-bf6d2429f896",
      carRentListing: {
        id: "4a1e9c2c-1r68-4e0c-90e4-4e210cf603ab",
        carContent: {
          id: "aea9cbbe-93b7-4e88-906d-85cd38209c41",
          userId: "deadbeef-dead-beef-dead-beefdeadbeef",
          brandId: "Li",
          modelId: "L7",
          yearOfCarProduction: 2024,
          fuelType: "FUEL_TYPE_DIESEL",
          transmission: "TRANSMISSION_TYPE_MANUAL",
          carBodyType: "CAR_BODY_TYPE_WAGON",
          vehicleSegment: "VEHICLE_SEGMENT_D",
          carOptions: {
            hasAirConditioning: false,
            hasChildSeat: true,
          },
          carCategory: "CAR_CATEGORY_ECONOMY",
          color: "Белый",
          photosUrl: ["car.svg", "car.svg", "car.svg"],
          createdAt: "2025-05-24T14:57:15.542674Z",
          updatedAt: "2025-05-24T14:57:15.542674Z",
        },
        userId: "deadbeef-dead-beef-dead-beefdeadbeef",
        listingOptions: {
          allowedForTaxi: false,
          allowedOnlyForPersonalUse: false,
          requireRussianCitizenship: false,
          buyoutPossible: true,
        },
        depositRequired: false,
        paymentPeriod: ["PAYMENT_PERIOD_DAILY"],
        pricePerDay: 2500,
        minimumRentalPeriod: 2,
        additionalInfo:
          "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д",
        createdAt: "2025-05-24T14:57:15.546472Z",
        updatedAt: "2025-05-24T14:57:15.546472Z",
        city: "Сочи",
        rentDuration: ["RENT_DURATION_FROM_WEEK"],
      },
    },
  },
  {
    listing: {
      id: "f30gd929-0g9e-6g1g-c6e6-dh8f4641h018",
      carRentListing: {
        id: "6c3g1e4e-3g8a-6g2e-b2g6-6g432eh825cd",
        carContent: {
          id: "cgc1eddf-b5d9-6g0a-b28f-a7ef5a42b163",
          userId: "deadbeef-dead-beef-dead-beefdeadbeef",
          brandId: "BMW",
          modelId: "BMW_M2",
          yearOfCarProduction: 2014,
          fuelType: "FUEL_TYPE_PETROL",
          transmission: "TRANSMISSION_TYPE_AUTOMATIC",
          carBodyType: "CAR_BODY_TYPE_SEDAN",
          vehicleSegment: "VEHICLE_SEGMENT_E",
          carOptions: {
            hasAirConditioning: true,
            hasChildSeat: true,
          },
          carCategory: "CAR_CATEGORY_BUSINESS",
          color: "Серебристый",
          photosUrl: ["car-large-2.svg", "car-large-2.svg", "car-large-2.svg"],
          createdAt: "2025-05-26T11:45:00.000000Z",
          updatedAt: "2025-05-26T11:45:00.000000Z",
        },
        userId: "deadbeef-dead-beef-dead-beefdeadbeef",
        listingOptions: {
          allowedForTaxi: false,
          allowedOnlyForPersonalUse: true,
          requireRussianCitizenship: true,
          buyoutPossible: true,
        },
        depositRequired: true,
        paymentPeriod: [
          "PAYMENT_PERIOD_DAILY",
          "PAYMENT_PERIOD_WEEKLY",
          "PAYMENT_PERIOD_MONTHLY",
        ],
        pricePerDay: 4500,
        minimumRentalPeriod: 3,
        additionalInfo:
          "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д",
        createdAt: "2025-05-26T11:45:00.000000Z",
        updatedAt: "2025-05-26T11:45:00.000000Z",
        city: "Санкт-Петербург",
        rentDuration: ["RENT_DURATION_FROM_WEEK", "RENT_DURATION_FROM_MONTH"],
      },
    },
  },
  {
    listing: {
      id: "f30gd929-0g9e-6g1g-c6e6-dh8f4641h028",
      carRentListing: {
        id: "6c3g1e4e-3g8a-6g2e-b2g6-6g432eh825cd",
        carContent: {
          id: "cgc1eddf-b5d9-6g0a-b28f-a7ef5a42b163",
          userId: "deadbeef-dead-beef-dead-beefdeadbeef",
          brandId: "BMW",
          modelId: "BMW_M2",
          yearOfCarProduction: 2014,
          fuelType: "FUEL_TYPE_PETROL",
          transmission: "TRANSMISSION_TYPE_AUTOMATIC",
          carBodyType: "CAR_BODY_TYPE_SEDAN",
          vehicleSegment: "VEHICLE_SEGMENT_E",
          carOptions: {
            hasAirConditioning: true,
            hasChildSeat: true,
          },
          carCategory: "CAR_CATEGORY_COMFORT_PLUS",
          color: "Серебристый",
          photosUrl: ["car-large-2.svg", "car-large-2.svg", "car-large-2.svg"],
          createdAt: "2025-05-26T11:45:00.000000Z",
          updatedAt: "2025-05-26T11:45:00.000000Z",
        },
        userId: "deadbeef-dead-beef-dead-beefdeadbeef",
        listingOptions: {
          allowedForTaxi: false,
          allowedOnlyForPersonalUse: true,
          requireRussianCitizenship: true,
          buyoutPossible: true,
        },
        depositRequired: true,
        paymentPeriod: [
          "PAYMENT_PERIOD_DAILY",
          "PAYMENT_PERIOD_WEEKLY",
          "PAYMENT_PERIOD_MONTHLY",
        ],
        pricePerDay: 4500,
        minimumRentalPeriod: 3,
        additionalInfo:
          "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д",
        createdAt: "2025-05-26T11:45:00.000000Z",
        updatedAt: "2025-05-26T11:45:00.000000Z",
        city: "Санкт-Петербург",
        rentDuration: ["RENT_DURATION_FROM_WEEK", "RENT_DURATION_FROM_MONTH"],
      },
    },
  },
  {
    listing: {
      id: "f30gd929-0g9e-6g1g-c6e6-dh8f4641h038",
      carRentListing: {
        id: "6c3g1e4e-3g8a-6g2e-b2g6-6g432eh825cd",
        carContent: {
          id: "cgc1eddf-b5d9-6g0a-b28f-a7ef5a42b163",
          userId: "deadbeef-dead-beef-dead-beefdeadbeef",
          brandId: "BMW",
          modelId: "BMW_M2",
          yearOfCarProduction: 2014,
          fuelType: "FUEL_TYPE_PETROL",
          transmission: "TRANSMISSION_TYPE_AUTOMATIC",
          carBodyType: "CAR_BODY_TYPE_SEDAN",
          vehicleSegment: "VEHICLE_SEGMENT_E",
          carOptions: {
            hasAirConditioning: true,
            hasChildSeat: true,
          },
          carCategory: "CAR_CATEGORY_BUSINESS",
          color: "Серебристый",
          photosUrl: ["car-large-2.svg", "car-large-2.svg", "car-large-2.svg"],
          createdAt: "2025-05-26T11:45:00.000000Z",
          updatedAt: "2025-05-26T11:45:00.000000Z",
        },
        userId: "deadbeef-dead-beef-dead-beefdeadbeef",
        listingOptions: {
          allowedForTaxi: false,
          allowedOnlyForPersonalUse: true,
          requireRussianCitizenship: true,
          buyoutPossible: true,
        },
        depositRequired: true,
        paymentPeriod: [
          "PAYMENT_PERIOD_DAILY",
          "PAYMENT_PERIOD_WEEKLY",
          "PAYMENT_PERIOD_MONTHLY",
        ],
        pricePerDay: 4500,
        minimumRentalPeriod: 3,
        additionalInfo:
          "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д",
        createdAt: "2025-05-26T11:45:00.000000Z",
        updatedAt: "2025-05-26T11:45:00.000000Z",
        city: "Санкт-Петербург",
        rentDuration: ["RENT_DURATION_FROM_WEEK", "RENT_DURATION_FROM_MONTH"],
      },
    },
  },
  {
    listing: {
      id: "f30gd929-0g9e-6g1g-c6e6-dh8f4641h068",
      carRentListing: {
        id: "6c3g1e4e-3g8a-6g2e-b2g6-6g432eh825cd",
        carContent: {
          id: "cgc1eddf-b5d9-6g0a-b28f-a7ef5a42b163",
          userId: "deadbeef-dead-beef-dead-beefdeadbeef",
          brandId: "BMW",
          modelId: "BMW_M2",
          yearOfCarProduction: 2014,
          fuelType: "FUEL_TYPE_PETROL",
          transmission: "TRANSMISSION_TYPE_AUTOMATIC",
          carBodyType: "CAR_BODY_TYPE_SEDAN",
          vehicleSegment: "VEHICLE_SEGMENT_E",
          carOptions: {
            hasAirConditioning: true,
            hasChildSeat: true,
          },
          carCategory: "CAR_CATEGORY_BUSINESS",
          color: "Серебристый",
          photosUrl: ["car-large-2.svg", "car-large-2.svg", "car-large-2.svg"],
          createdAt: "2025-05-26T11:45:00.000000Z",
          updatedAt: "2025-05-26T11:45:00.000000Z",
        },
        userId: "deadbeef-dead-beef-dead-beefdeadbeef",
        listingOptions: {
          allowedForTaxi: false,
          allowedOnlyForPersonalUse: true,
          requireRussianCitizenship: true,
          buyoutPossible: true,
        },
        depositRequired: true,
        paymentPeriod: [
          "PAYMENT_PERIOD_DAILY",
          "PAYMENT_PERIOD_WEEKLY",
          "PAYMENT_PERIOD_MONTHLY",
        ],
        pricePerDay: 4500,
        minimumRentalPeriod: 3,
        additionalInfo:
          "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д",
        createdAt: "2025-05-26T11:45:00.000000Z",
        updatedAt: "2025-05-26T11:45:00.000000Z",
        city: "Санкт-Петербург",
        rentDuration: ["RENT_DURATION_FROM_WEEK", "RENT_DURATION_FROM_MONTH"],
      },
    },
  },
  {
    listing: {
      id: "e29fc818-9f8d-5f0f-b5d5-cg7e3530g9297",
      carRentListing: {
        id: "5b2f0d3d-2f79-5f1d-a1f5-5f321dg714bc",
        carContent: {
          id: "bfb0dcce-a4c8-5f99-a17e-96de4931a052",
          userId: "deadbeef-dead-beef-dead-beefdeadbeef",
          brandId: "AUDI",
          modelId: "AUDI_A6",
          yearOfCarProduction: 2022,
          fuelType: "FUEL_TYPE_PETROL",
          transmission: "TRANSMISSION_TYPE_AUTOMATIC",
          carBodyType: "CAR_BODY_TYPE_SEDAN",
          vehicleSegment: "VEHICLE_SEGMENT_E",
          carOptions: {
            hasAirConditioning: true,
            hasChildSeat: false,
          },
          carCategory: "CAR_CATEGORY_BUSINESS",
          color: "Черный",
          photosUrl: ["car-large.svg", "car-large.svg", "car-large.svg"],
          createdAt: "2025-05-25T10:30:00.000000Z",
          updatedAt: "2025-05-25T10:30:00.000000Z",
        },
        userId: "deadbeef-dead-beef-dead-beefdeadbeef",
        listingOptions: {
          allowedForTaxi: true,
          allowedOnlyForPersonalUse: true,
          requireRussianCitizenship: true,
          buyoutPossible: true,
        },
        depositRequired: true,
        paymentPeriod: ["PAYMENT_PERIOD_DAILY", "PAYMENT_PERIOD_WEEKLY"],
        pricePerDay: 3500,
        minimumRentalPeriod: 1,
        additionalInfo:
          "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д",
        createdAt: "2025-05-25T10:30:00.000000Z",
        updatedAt: "2025-05-25T10:30:00.000000Z",
        city: "Москва",
        rentDuration: ["RENT_DURATION_FROM_DAY", "RENT_DURATION_FROM_WEEK"],
      },
    },
  },
  {
    listing: {
      id: "e29fc818-9f8d-5f0f-b5d5-cg7e3533g9097",
      carRentListing: {
        id: "5b2f0d3d-2f79-5f1d-a1f5-5f321dg714bc",
        carContent: {
          id: "bfb0dcce-a4c8-5f99-a17e-96de4931a052",
          userId: "deadbeef-dead-beef-dead-beefdeadbeef",
          brandId: "AUDI",
          modelId: "AUDI_A6",
          yearOfCarProduction: 2022,
          fuelType: "FUEL_TYPE_PETROL",
          transmission: "TRANSMISSION_TYPE_AUTOMATIC",
          carBodyType: "CAR_BODY_TYPE_SEDAN",
          vehicleSegment: "VEHICLE_SEGMENT_E",
          carOptions: {
            hasAirConditioning: true,
            hasChildSeat: false,
          },
          carCategory: "CAR_CATEGORY_BUSINESS",
          color: "Черный",
          photosUrl: ["car-large.svg", "car-large.svg", "car-large.svg"],
          createdAt: "2025-05-25T10:30:00.000000Z",
          updatedAt: "2025-05-25T10:30:00.000000Z",
        },
        userId: "deadbeef-dead-beef-dead-beefdeadbeef",
        listingOptions: {
          allowedForTaxi: true,
          allowedOnlyForPersonalUse: true,
          requireRussianCitizenship: true,
          buyoutPossible: true,
        },
        depositRequired: true,
        paymentPeriod: ["PAYMENT_PERIOD_DAILY", "PAYMENT_PERIOD_WEEKLY"],
        pricePerDay: 3500,
        minimumRentalPeriod: 1,
        additionalInfo:
          "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д",
        createdAt: "2025-05-25T10:30:00.000000Z",
        updatedAt: "2025-05-25T10:30:00.000000Z",
        city: "Москва",
        rentDuration: ["RENT_DURATION_FROM_DAY", "RENT_DURATION_FROM_WEEK"],
      },
    },
  },
  {
    listing: {
      id: "e29fc818-5f8d-5f0f-b5d5-cg7e3530g9097",
      carRentListing: {
        id: "5b2f0d3d-2f79-5f1d-a1f5-5f321dg714bc",
        carContent: {
          id: "bfb0dcce-a4c8-5f99-a17e-96de4931a052",
          userId: "deadbeef-dead-beef-dead-beefdeadbeef",
          brandId: "AUDI",
          modelId: "AUDI_A6",
          yearOfCarProduction: 2022,
          fuelType: "FUEL_TYPE_PETROL",
          transmission: "TRANSMISSION_TYPE_AUTOMATIC",
          carBodyType: "CAR_BODY_TYPE_SEDAN",
          vehicleSegment: "VEHICLE_SEGMENT_E",
          carOptions: {
            hasAirConditioning: true,
            hasChildSeat: false,
          },
          carCategory: "CAR_CATEGORY_BUSINESS",
          color: "Черный",
          photosUrl: ["car-large.svg", "car-large.svg", "car-large.svg"],
          createdAt: "2025-05-25T10:30:00.000000Z",
          updatedAt: "2025-05-25T10:30:00.000000Z",
        },
        userId: "deadbeef-dead-beef-dead-beefdeadbeef",
        listingOptions: {
          allowedForTaxi: true,
          allowedOnlyForPersonalUse: true,
          requireRussianCitizenship: true,
          buyoutPossible: true,
        },
        depositRequired: true,
        paymentPeriod: ["PAYMENT_PERIOD_DAILY", "PAYMENT_PERIOD_WEEKLY"],
        pricePerDay: 3500,
        minimumRentalPeriod: 1,
        additionalInfo:
          "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д",
        createdAt: "2025-05-25T10:30:00.000000Z",
        updatedAt: "2025-05-25T10:30:00.000000Z",
        city: "Москва",
        rentDuration: ["RENT_DURATION_FROM_DAY", "RENT_DURATION_FROM_WEEK"],
      },
    },
  },
  {
    listing: {
      id: "d18ec707-8f7c-4e9e-a4c4-bf6d2429f886",
      size: "large",
      carRentListing: {
        id: "4a1e9c2c-1e68-4e0c-90e4-4e210cf603ab",
        carContent: {
          id: "aea9cbbe-93b7-4e88-906d-85cd38209c41",
          userId: "deadbeef-dead-beef-dead-beefdeadbeef",
          brandId: "TOYOTA",
          modelId: "Land Cruiser 200",
          yearOfCarProduction: 2024,
          fuelType: "FUEL_TYPE_DIESEL",
          transmission: "TRANSMISSION_TYPE_AUTOMATIC",
          carBodyType: "CAR_BODY_TYPE_SUV",
          vehicleSegment: "VEHICLE_SEGMENT_D",
          carOptions: {
            hasAirConditioning: true,
            hasChildSeat: true,
          },
          carCategory: "CAR_CATEGORY_BUSINESS",
          color: "Черный",
          photosUrl: [
            "car-large.svg",
            "car-large.svg",
            "car-large.svg",
            "car-large.svg",
            "car-large.svg",
          ],
          createdAt: "2025-03-15T12:34:56Z",
          updatedAt: "2025-03-15T12:34:56Z",
        },
        userId: "deadbeef-dead-beef-dead-beefdeadbeef",
        listingOptions: {
          allowedForTaxi: false,
          allowedOnlyForPersonalUse: false,
          requireRussianCitizenship: false,
          buyoutPossible: true,
        },
        depositRequired: false,
        paymentPeriod: ["PAYMENT_PERIOD_DAILY"],
        pricePerDay: 12000,
        minimumRentalPeriod: 1,
        additionalInfo:
          "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д",
        createdAt: "2025-03-15T12:34:56Z",
        updatedAt: "2025-03-15T12:34:56Z",
        city: "Новокузнецк",
        rentDuration: ["RENT_DURATION_FROM_DAY"],
      },
    },
  },
  {
    listing: {
      id: "d18ec707-8f7c-4e9e-a4c4-bf6d2429f897",
      carRentListing: {
        id: "4a1e9c2c-1e68-4e0c-90e4-4e210cf603ac",
        carContent: {
          id: "aea9cbbe-93b7-4e88-906d-85cd38209c42",
          userId: "deadbeef-dead-beef-dead-beefdeadbeef",
          brandId: "Li",
          modelId: "L7",
          yearOfCarProduction: 2024,
          fuelType: "FUEL_TYPE_DIESEL",
          transmission: "TRANSMISSION_TYPE_AUTOMATIC",
          carBodyType: "CAR_BODY_TYPE_SEDAN",
          vehicleSegment: "VEHICLE_SEGMENT_D",
          carOptions: {
            hasAirConditioning: true,
            hasChildSeat: true,
          },
          carCategory: "CAR_CATEGORY_COMFORT_PLUS",
          color: "Белый",
          photosUrl: ["car.svg"],
          createdAt: "2025-04-07T12:34:56Z",
          updatedAt: "2025-04-07T12:34:56Z",
        },
        userId: "deadbeef-dead-beef-dead-beefdeadbeef",
        listingOptions: {
          allowedForTaxi: false,
          allowedOnlyForPersonalUse: false,
          requireRussianCitizenship: false,
          buyoutPossible: true,
        },
        depositRequired: false,
        paymentPeriod: ["PAYMENT_PERIOD_DAILY"],
        pricePerDay: 12000,
        minimumRentalPeriod: 1,
        additionalInfo:
          "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д",
        createdAt: "2025-04-07T12:34:56Z",
        updatedAt: "2025-04-07T12:34:56Z",
        city: "Иркутск",
        rentDuration: ["RENT_DURATION_FROM_DAY"],
      },
    },
  },
  {
    listing: {
      id: "d18ec707-8f1c-4e9e-a4c4-bf6d2429f886",
      size: "large",
      carRentListing: {
        id: "4a1e9c2c-1e68-4e0c-90e4-4e210cf603ab",
        carContent: {
          id: "aea9cbbe-93b7-4e88-906d-85cd38209c41",
          userId: "deadbeef-dead-beef-dead-beefdeadbeef",
          brandId: "TOYOTA",
          modelId: "Land Cruiser 200",
          yearOfCarProduction: 2024,
          fuelType: "FUEL_TYPE_DIESEL",
          transmission: "TRANSMISSION_TYPE_AUTOMATIC",
          carBodyType: "CAR_BODY_TYPE_SUV",
          vehicleSegment: "VEHICLE_SEGMENT_D",
          carOptions: {
            hasAirConditioning: true,
            hasChildSeat: true,
          },
          carCategory: "CAR_CATEGORY_BUSINESS",
          color: "Черный",
          photosUrl: [
            "car-large.svg",
            "car-large.svg",
            "car-large.svg",
            "car-large.svg",
            "car-large.svg",
          ],
          createdAt: "2025-03-15T12:34:56Z",
          updatedAt: "2025-03-15T12:34:56Z",
        },
        userId: "deadbeef-dead-beef-dead-beefdeadbeef",
        listingOptions: {
          allowedForTaxi: false,
          allowedOnlyForPersonalUse: false,
          requireRussianCitizenship: false,
          buyoutPossible: true,
        },
        depositRequired: false,
        paymentPeriod: ["PAYMENT_PERIOD_DAILY"],
        pricePerDay: 12000,
        minimumRentalPeriod: 1,
        additionalInfo:
          "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д",
        createdAt: "2025-03-15T12:34:56Z",
        updatedAt: "2025-03-15T12:34:56Z",
        city: "Новокузнецк",
        rentDuration: ["RENT_DURATION_FROM_DAY"],
      },
    },
  },
];
