export const cars = [
  {
    common: {
      id: "1",
      photos: ["car.svg", "car.svg", "car.svg", "car.svg", "car.svg"],
      title: "Аренда Li L7 2024",
      description:
        "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д ",
      ads: true,
      city: "Москва",
      district: "Центральный",
      address: "г. Москва, Ярославское шоссе, д 6",
      category: "RENT_AUTO",
      created_at: "2025-04-11T12:34:56Z",
    },
    rent_auto: {
      cost_per_day: 11000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
    daily_rent: {
      delivery_possible: true,
    },
  },
  {
    common: {
      id: "2",
      photos: [
        "car-large.svg",
        "car-large.svg",
        "car-large.svg",
        "car-large.svg",
        "car-large.svg",
      ],
      title: "Аренда TOYOTA Land Cruiser 200",
      description:
        "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д ",
      city: "Санкт-Петербург",
      district: "Адмиралтейский",
      address: "г. Москва, Ярославское шоссе, д 6",
      category: "RENT_AUTO",
      created_at: "2025-04-20T12:34:56Z",
    },
    rent_auto: {
      cost_per_day: 10000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
    daily_rent: {
      delivery_possible: true,
    },
  },
  {
    common: {
      id: "3",
      photos: ["car.svg"],
      title: "Аренда Li L7 2024",
      description:
        "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д ",
      city: "Новосибирск",
      district: "Центральный",
      address: "г. Москва, Ярославское шоссе, д 6",
      category: "RENT_AUTO",
      created_at: "2025-04-08T12:34:56Z",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
    daily_rent: {
      delivery_possible: false,
    },
  },
  {
    common: {
      id: "4",
      photos: ["car.svg"],
      title: "Аренда Li L7 2024",
      description:
        "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д ",
      ads: true,
      city: "Екатеринбург",
      district: "Ленинский",
      address: "г. Москва, Ярославское шоссе, д 6",
      category: "DAILY_RENT",
      created_at: "2025-04-10T12:34:56Z",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
    daily_rent: {
      delivery_possible: false,
      cost_per_day: 12000,
      buy_option: true,
    },
  },
  {
    common: {
      id: "5",
      photos: ["car.svg"],
      title: "Аренда Li L7 2024",
      description:
        "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д ",
      city: "Казань",
      district: "Вахитовский",
      address: "г. Москва, Ярославское шоссе, д 6",
      category: "RENT_AUTO",
      created_at: "2025-03-20T12:34:56Z",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
    daily_rent: {
      delivery_possible: false,
    },
  },
  {
    common: {
      id: "6",
      photos: ["car-large.svg", "car-large.svg", "car-large.svg"],
      title: "Аренда TOYOTA Land Cruiser 200",
      description:
        "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д ",
      city: "Нижний Новгород",
      district: "Нижегородский",
      address: "г. Москва, Ярославское шоссе, д 6",
      category: "RENT_AUTO",
      created_at: "2025-04-13T12:34:56Z",
      size: "large",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
    daily_rent: {
      delivery_possible: false,
    },
  },
  {
    common: {
      id: "7",
      photos: ["car.svg"],
      title: "Аренда Li L7 2024",
      description:
        "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д ",
      city: "Челябинск",
      district: "Центральный",
      address: "г. Москва, Ярославское шоссе, д 6",
      category: "DAILY_RENT",
      created_at: "2025-03-21T12:34:56Z",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
    daily_rent: {
      delivery_possible: true,
      cost_per_day: 11000,
      buy_option: true,
    },
  },
  {
    common: {
      id: "8",
      photos: ["car.svg"],
      title: "Аренда Li L7 2024",
      description:
        "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д ",
      city: "Самара",
      district: "Самарский",
      address: "г. Москва, Ярославское шоссе, д 6",
      category: "RENT_AUTO",
      created_at: "2025-01-20T12:34:56Z",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
    daily_rent: {
      delivery_possible: true,
    },
  },
  {
    common: {
      id: "9",
      photos: ["car.svg"],
      title: "Аренда Li L7 2024",
      description:
        "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д ",
      city: "Омск",
      district: "Центральный",
      address: "г. Москва, Ярославское шоссе, д 6",
      category: "DAILY_RENT",
      created_at: "2025-03-27T12:34:56Z",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
    daily_rent: {
      delivery_possible: false,
      cost_per_day: 12000,
      buy_option: true,
    },
  },
  {
    common: {
      id: "10",
      photos: ["car.svg"],
      title: "Аренда Li L7 2024",
      description:
        "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д ",
      city: "Ростов-на-Дону",
      district: "Ленинский",
      address: "г. Москва, Ярославское шоссе, д 6",
      category: "RENT_AUTO",
      created_at: "2025-04-15T12:34:56Z",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
    daily_rent: {
      delivery_possible: true,
    },
  },
  {
    common: {
      id: "11",
      photos: ["car-large.svg", "car-large.svg", "car-large.svg"],
      title: "Аренда TOYOTA Land Cruiser 200",
      description:
        "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д ",
      city: "Уфа",
      district: "Советский",
      address: "г. Москва, Ярославское шоссе, д 6",
      category: "RENT_AUTO",
      created_at: "2024-07-20T12:34:56Z",
      size: "large",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
    daily_rent: {
      delivery_possible: false,
    },
  },
  {
    common: {
      id: "12",
      photos: ["car.svg"],
      title: "Аренда Li L7 2024",
      description:
        "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д ",
      city: "Красноярск",
      district: "Центральный",
      address: "г. Москва, Ярославское шоссе, д 6",
      category: "DAILY_RENT",
      created_at: "2025-02-20T12:34:56Z",
    },
    rent_auto: {
      cost_per_day: 13000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
    search_auto: {
      car_class: "comfort_plus",
    },
    daily_rent: {
      delivery_possible: true,
      cost_per_day: 13000,
      buy_option: true,
    },
  },
  {
    common: {
      id: "13",
      photos: ["car-large.svg", "car-large.svg", "car-large.svg"],
      title: "Аренда TOYOTA Land Cruiser 200",
      description:
        "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д ",
      city: "Пермь",
      district: "Дзержинский",
      address: "г. Москва, Ярославское шоссе, д 6",
      category: "BUY_AUTO",
      created_at: "2024-01-10T12:34:56Z",
      size: "large",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
    search_auto: {
      car_class: "comfort_plus",
    },
    daily_rent: {
      delivery_possible: false,
    },
  },
  {
    common: {
      id: "14",
      photos: ["car-large-2.svg", "car-large-2.svg", "car-large-2.svg"],
      title: "Аренда Li L7 2024",
      description:
        "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д ",
      city: "Воронеж",
      district: "Левобережный",
      address: "г. Москва, Ярославское шоссе, д 6",
      category: "BUY_AUTO",
      created_at: "2025-04-22T12:34:56Z",
      size: "large",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
    daily_rent: {
      delivery_possible: false,
    },
  },
  {
    common: {
      id: "15",
      photos: ["car.svg"],
      title: "Аренда Li L7 2024",
      description:
        "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д ",
      city: "Волгоград",
      district: "Центральный",
      address: "г. Москва, Ярославское шоссе, д 6",
      category: "BUY_AUTO",
      created_at: "2025-03-01T12:34:56Z",
    },
    rent_auto: {
      cost_per_day: 11000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
    search_auto: {
      car_class: "comfort_plus",
    },
    daily_rent: {
      delivery_possible: false,
    },
  },
  {
    common: {
      id: "16",
      photos: ["car.svg"],
      title: "Аренда Li L7 2024",
      description:
        "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д ",
      city: "Краснодар",
      district: "Центральный",
      address: "г. Москва, Ярославское шоссе, д 6",
      category: "BUY_AUTO",
      created_at: "2025-04-18T12:34:56Z",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
    daily_rent: {
      delivery_possible: false,
    },
  },
  {
    common: {
      id: "17",
      photos: ["car-large-2.svg", "car-large-2.svg", "car-large-2.svg"],
      title: "Аренда Li L7 2024",
      description:
        "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д ",
      city: "Саратов",
      district: "Фрунзенский",
      address: "г. Москва, Ярославское шоссе, д 6",
      category: "BUY_AUTO",
      created_at: "2025-04-17T12:34:56Z",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
    daily_rent: {
      delivery_possible: false,
    },
  },
  {
    common: {
      id: "18",
      photos: ["car.svg"],
      title: "Аренда Li L7 2024",
      description:
        "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д ",
      city: "Тюмень",
      district: "Центральный",
      address: "г. Москва, Ярославское шоссе, д 6",
      category: "DRIVER_JOBS",
      created_at: "2025-04-16T12:34:56Z",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
    daily_rent: {
      delivery_possible: true,
    },
    driver_job: {
      cost_per_day: 13000,
      buy_option: true,
    },
  },
  {
    common: {
      id: "19",
      photos: ["car-large.svg", "car-large.svg", "car-large.svg"],
      title: "Аренда TOYOTA Land Cruiser 200",
      description:
        "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д ",
      ads: true,
      city: "Ижевск",
      district: "Октябрьский",
      address: "г. Москва, Ярославское шоссе, д 6",
      category: "DRIVER_JOBS",
      created_at: "2025-04-14T12:34:56Z",
    },
    rent_auto: {
      cost_per_day: 12000,
      buy_option: true,
      taxi_possible: false,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
    daily_rent: {
      delivery_possible: true,
    },
    driver_job: {
      cost_per_day: 12000,
      buy_option: true,
    },
  },
  {
    common: {
      id: "20",
      photos: ["car-large-2.svg", "car-large-2.svg", "car-large-2.svg"],
      title: "Аренда Li L7 2024",
      description:
        "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д ",
      city: "Москва",
      district: "Северный",
      address: "г. Москва, Ярославское шоссе, д 6",
      category: "DRIVER_JOBS",
      created_at: "2025-04-12T12:34:56Z",
      size: "large",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
    search_auto: {
      car_class: "comfort_plus",
    },
    daily_rent: {
      delivery_possible: true,
    },
    driver_job: {
      cost_per_day: 13000,
      buy_option: true,
    },
  },
  {
    common: {
      id: "21",
      photos: ["car.svg"],
      title: "Аренда Li L7 2024",
      description:
        "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д ",
      ads: true,
      city: "Ульяновск",
      district: "Ленинский",
      address: "г. Москва, Ярославское шоссе, д 6",
      category: "DRIVER_JOBS",
      created_at: "2025-04-09T12:34:56Z",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
    daily_rent: {
      delivery_possible: false,
    },
    driver_job: {
      cost_per_day: 12000,
      buy_option: true,
    },
  },
  {
    common: {
      id: "22",
      photos: ["car.svg"],
      title: "Аренда Li L7 2024",
      description:
        "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д ",
      city: "Иркутск",
      district: "Правобережный",
      address: "г. Москва, Ярославское шоссе, д 6",
      category: "DRIVER_JOBS",
      created_at: "2025-04-07T12:34:56Z",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
    daily_rent: {
      delivery_possible: false,
    },
    driver_job: {
      cost_per_day: 12000,
      buy_option: true,
    },
  },
  {
    common: {
      id: "23",
      photos: ["car-large.svg", "car-large.svg", "car-large.svg"],
      title: "Аренда TOYOTA Land Cruiser 200",
      description:
        "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д ",
      ads: true,
      city: "Москва",
      district: "Западный",
      address: "г. Москва, Ярославское шоссе, д 6",
      category: "DRIVER_JOBS",
      created_at: "2025-04-05T12:34:56Z",
      size: "large",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
    daily_rent: {
      delivery_possible: false,
    },
    driver_job: {
      cost_per_day: 11000,
      buy_option: true,
    },
  },
  {
    common: {
      id: "24",
      photos: ["car-large.svg", "car-large.svg", "car-large.svg"],
      title: "Аренда TOYOTA Land Cruiser 200",
      description:
        "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д ",
      city: "Ярославль",
      district: "Кировский",
      address: "г. Москва, Ярославское шоссе, д 6",
      category: "AUTO_SERVICES",
      created_at: "2025-04-03T12:34:56Z",
      size: "large",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
    search_auto: {
      car_class: "comfort_plus",
    },
    daily_rent: {
      delivery_possible: false,
    },
  },
  {
    common: {
      id: "25",
      photos: ["car-large.svg", "car-large.svg", "car-large.svg"],
      title: "Аренда TOYOTA Land Cruiser 200",
      description:
        "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д ",
      city: "Владивосток",
      district: "Ленинский",
      address: "г. Москва, Ярославское шоссе, д 6",
      category: "AUTO_SERVICES",
      created_at: "2025-04-01T12:34:56Z",
      size: "large",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
    daily_rent: {
      delivery_possible: false,
    },
  },
  {
    common: {
      id: "26",
      photos: ["car.svg"],
      title: "Аренда Li L7 2024",
      description:
        "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д ",
      city: "Махачкала",
      district: "Советский",
      address: "г. Москва, Ярославское шоссе, д 6",
      category: "AUTO_SERVICES",
      created_at: "2025-03-28T12:34:56Z",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
    daily_rent: {
      delivery_possible: true,
    },
  },
  {
    common: {
      id: "27",
      photos: ["car.svg"],
      title: "Аренда Li L7 2024",
      description:
        "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д ",
      city: "Томск",
      district: "Кировский",
      address: "г. Москва, Ярославское шоссе, д 6",
      category: "AUTO_SERVICES",
      created_at: "2025-03-25T12:34:56Z",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
    daily_rent: {
      delivery_possible: true,
    },
  },
  {
    common: {
      id: "28",
      photos: ["car.svg"],
      title: "Аренда Li L7 2024",
      description:
        "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д ",
      city: "Оренбург",
      district: "Центральный",
      address: "г. Москва, Ярославское шоссе, д 6",
      category: "AUTO_SERVICES",
      created_at: "2025-03-22T12:34:56Z",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
    daily_rent: {
      delivery_possible: false,
    },
  },
  {
    common: {
      id: "29",
      photos: ["car.svg"],
      title: "Аренда Li L7 2024",
      description:
        "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д ",
      city: "Кемерово",
      district: "Центральный",
      address: "г. Москва, Ярославское шоссе, д 6",
      category: "AUTO_SERVICES",
      created_at: "2025-03-18T12:34:56Z",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
    daily_rent: {
      delivery_possible: true,
    },
  },
  {
    common: {
      id: "30",
      photos: [
        "car-large.svg",
        "car-large.svg",
        "car-large.svg",
        "car-large.svg",
        "car-large.svg",
      ],
      title: "Аренда TOYOTA Land Cruiser 200",
      description:
        "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д ",
      city: "Новокузнецк",
      district: "Центральный",
      address: "г. Москва, Ярославское шоссе, д 6",
      category: "AUTO_SERVICES",
      created_at: "2025-03-15T12:34:56Z",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
    daily_rent: {
      delivery_possible: true,
    },
  },
  {
    common: {
      id: "31",
      photos: ["car.svg"],
      title: "Аренда Li L7 2024",
      description:
        "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д ",
      city: "Рязань",
      district: "Советский",
      address: "г. Москва, Ярославское шоссе, д 6",
      category: "AUTO_SERVICES",
      created_at: "2025-03-12T12:34:56Z",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
    search_auto: {
      car_class: "comfort_plus",
    },
    daily_rent: {
      delivery_possible: false,
    },
  },
  {
    common: {
      id: "32",
      photos: ["car.svg"],
      title: "Аренда Li L7 2024",
      description:
        "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д ",
      city: "Пенза",
      district: "Ленинский",
      address: "г. Москва, Ярославское шоссе, д 6",
      category: "AUTO_SERVICES",
      created_at: "2025-03-10T12:34:56Z",
    },
    rent_auto: {
      cost_per_day: 12000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
    search_auto: {
      car_class: "comfort_plus",
    },
    daily_rent: {
      delivery_possible: false,
    },
  },
  {
    common: {
      id: "33",
      photos: [
        "car-large-2.svg",
        "car-large-2.svg",
        "car-large-2.svg",
        "car-large-2.svg",
        "car-large-2.svg",
      ],
      title: "Аренда Li L7 2024",
      description:
        "Mашина aбcолютнo новaя комплектация Ultimаtе. Куплeна в 2024 гoду в сaлонe у официального дилеpa зa наличку, все чеки имеются. Машина на гарантии, русификация, полный пакет документов и.т. д. Машина на гарантии, русификация, полный пакет документов и.т. д  ",
      city: "Пенза",
      district: "Октябрьский",
      address: "г. Москва, Ярославское шоссе, д 6",
      category: "AUTO_SERVICES",
      created_at: "2025-03-05T12:34:56Z",
      size: "large",
      ads: true,
    },
    rent_auto: {
      cost_per_day: 14000,
      taxi_possible: false,
      buy_option: true,
      year: 2024,
      color: "black",
      discount: 0,
      min_rental_period_days: 1,
    },
    search_auto: {
      car_class: "comfort_plus",
    },
    daily_rent: {
      delivery_possible: false,
    },
    auto_services: {
      cost_per_day: 14000,
      buy_option: true,
    },
  },
];
